azureproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('restaurant_review.urls')),
    path('admin/', admin.site.urls),
]

restaurant_review/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.details, name='details'),
    path('create', views.create_restaurant, name='create_restaurant'),
    path('add', views.add_restaurant, name='add_restaurant'),
    path('review/<int:id>', views.add_review, name='add_review'),
]

restaurant_review/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator 

# Create your models here.
class Restaurant(models.Model):
    name = models.CharField(max_length=50)
    street_address = models.CharField(max_length=50)
    description = models.CharField(max_length=250)
    def __str__(self):
        return self.name

class Review(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    user_name = models.CharField(max_length=20)
    rating=models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    review_text = models.CharField(max_length=500)
    review_date = models.DateTimeField('review date')    
    def __str__(self):
        return self.restaurant.name + " (" + self.review_date.strftime("%x") +")"

restaurant_review/views.py
import uuid
import os
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.db.models import Avg, Count
from django.urls import reverse
from django.utils import timezone
from django.contrib import messages
from requests import RequestException, exceptions

from restaurant_review.models import Restaurant, Review

# Create your views here.

def index(request):
    print('Request for index page received')
    restaurants = Restaurant.objects.annotate(avg_rating=Avg('review__rating')).annotate(review_count=Count('review'))
    return render(request, 'restaurant_review/index.html', {'restaurants': restaurants })


def details(request, id):
    print('Request for restaurant details page received')

    try: 
        restaurant = Restaurant.objects.annotate(avg_rating=Avg('review__rating')).annotate(review_count=Count('review')).get(pk=id)
    except Restaurant.DoesNotExist:
        raise Http404("Restaurant doesn't exist")
    return render(request, 'restaurant_review/details.html', {'restaurant': restaurant})


def create_restaurant(request):
    print('Request for add restaurant page received')

    return render(request, 'restaurant_review/create_restaurant.html')

def add_restaurant(request):
    try:
        name = request.POST['restaurant_name']
        street_address = request.POST['street_address']
        description = request.POST['description']
        if (name == "" or description == ""):
            raise RequestException()
    except (KeyError, exceptions.RequestException) as e:
        # Redisplay the restaurant entry form.
        messages.add_message(request, messages.INFO, 'Restaurant not added. Include at least a restaurant name and description.')
        return HttpResponseRedirect(reverse('create_restaurant'))  
    else:
        restaurant = Restaurant()
        restaurant.name = name
        restaurant.street_address = street_address
        restaurant.description = description
        Restaurant.save(restaurant)
                
        return HttpResponseRedirect(reverse('details', args=(restaurant.id,)))

def add_review(request, id):
    try: 
        restaurant = Restaurant.objects.annotate(avg_rating=Avg('review__rating')).annotate(review_count=Count('review')).get(pk=id)
    except Restaurant.DoesNotExist:
        raise Http404("Restaurant doesn't exist")

    try:
        user_name = request.POST['user_name']
        rating = request.POST['rating']
        review_text = request.POST['review_text']
        if (user_name == "" or rating == ""):
            raise RequestException()            
    except (KeyError, exceptions.RequestException) as e:
        # Redisplay the details page
        messages.add_message(request, messages.INFO, 'Review not added. Include at least a name and rating for review.')
        return HttpResponseRedirect(reverse('details', args=(id,)))  
    else:
        review = Review()
        review.restaurant = restaurant
        review.review_date = timezone.now()
        review.user_name = user_name
        review.rating = rating
        review.review_text = review_text
        Review.save(review)
                
    return HttpResponseRedirect(reverse('details', args=(id,)))

restaurant_review/templates/restaurant_review/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <title>Django web app with PostgreSQL in Azure - {% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" >
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" >
        <link rel="stylesheet" type="text/css" href="{% static 'restaurant.css' %}" />
        <link rel="icon" href="{% static 'favicon.ico' %}" >
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
        <div class="container">
          <a class="navbar-brand" href="/">
            <img src="{% static '/images/azure-icon.svg' %}" alt="" width="30" height="24" class="d-inline-block align-text-top">
            Azure Restaurant Review
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">                
            <ul class="navbar-nav mb-2 mb-md-0 ms-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown07XL" data-bs-toggle="dropdown" aria-expanded="true">Azure Docs</a>
                    <ul class="dropdown-menu" aria-labelledby="dropdown07XL" data-bs-popper="none">
                      <li><a class="dropdown-item" target="_blank" href="https://docs.microsoft.com/azure">Azure Docs Home</a></li>
                      <li><a class="dropdown-item" target="_blank" href="https://docs.microsoft.com/azure/developer/python/tutorial-python-managed-identity-01">This tutorial in the Developer Center</a></li>
                      <li><a class="dropdown-item" target="_blank" href="https://docs.microsoft.com/azure/developer/python">Python on Azure Developer Center</a></li>
                      <li><a class="dropdown-item" target="_blank" href="https://azure.microsoft.com/develop/python/">Python on Azure</a></li>
                    </ul>
                </li>
            </ul>
          </div>
        </div>
      </nav>

      <main class="container">    
        {% block content %}{% endblock %}
      </main>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

restaurant_review/templates/restaurant_review/create_restaurant.html
{% extends "restaurant_review/base.html" %}
{% block title %}Restaurant Create{% endblock %}
{% block content %}
    <h1>Add New Restaurant</h1>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <form method="POST" action="{% url 'add_restaurant' %}">{% csrf_token %}
        <div class="mb-3">
          <label for="restaurant_name" class="form-label">Name</label>
          <input type="text" class="form-control" id="restaurant_name" name="restaurant_name">
        </div>
        <div class="mb-3">
          <label for="street_address" class="form-label">Street Address</label>
          <input type="text" class="form-control" id="street_address" name="street_address">
        </div>
        <div class="mb-3">
            <label for="description" class="form-label">Description</label>
            <input type="text" class="form-control" id="description" name="description">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="cancel" class="btn btn-primary">Cancel</button>
      </form>
{% endblock %}
         

restaurant_review/templates/restaurant_review/details.html
{% extends "restaurant_review/base.html" %}
{% load restaurant_extras %}
{% block title %}Restaurant Details{% endblock %}
{% block content %}
    <h1>{{ restaurant.name }}</h1>

    <div class="row">
        <div class="col-md-2 fw-bold">Street address:</div>
        <div class="col">{{ restaurant.street_address }}</div>
    </div>
    <div class="row">
        <div class="col-md-2 fw-bold">Description:</div>
        <div class="col">{{ restaurant.description }}</div>                
    </div>
    <div class="row">
        <div class="col-md-2 fw-bold">Rating:</div>
        <div class="col"> {% star_rating restaurant.avg_rating restaurant.review_count  %} </div>                
    </div>

    <h4 class="mt-5">Reviews</h4>

    <p>
        <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#addReviewModal">
            Add new review
        </button>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </p>

    <!-- Button trigger modal -->
    {% if restaurant.review_set %}
        <table class="table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>User</th>
                    <th>Rating</th>
                    <th>Review</th>
                </tr>
            </thead>
            <tbody>
                {% for review in restaurant.review_set.all %}
                    <tr>
                        <td>{{ review.review_date }}</td>
                        <td>{{ review.user_name }}</td>
                        <td>{{ review.rating }}</td>
                        <td>{{ review.review_text }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No reviews of this restaurant yet.</p>
    {% endif %}

    <!-- Modal -->
    <div class="modal fade" id="addReviewModal" tabindex="-1" aria-labelledby="addReviewModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="addReviewModalLabel">Add Review</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
              <form method="POST" action="{% url 'add_review' restaurant.id %}" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="modal-body">

                <div class="mb-3">                        
                    <label for="user_name" class="form-label fw-bold">Your name</label>
                    <input type="text" class="form-control" id="user_name" name="user_name">
                  </div>
                  <div class="mb-3">
                    <label class="form-label fw-bold">Rating</label>

                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="rating" id="rating1" value="1">
                        <label class="form-check-label" for="rating1">1</label>
                      </div>
                      <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="rating" id="rating2" value="2">
                        <label class="form-check-label" for="rating2">2</label>
                      </div>
                      <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="rating" id="rating3" value="3">
                        <label class="form-check-label" for="rating3">3</label>
                      </div>
                      <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="rating" id="rating4" value="4">
                        <label class="form-check-label" for="rating3">4</label>
                      </div>
                      <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="rating" id="rating5" value="5">
                        <label class="form-check-label" for="rating3">5</label>
                      </div>
                  </div>
                  <div class="mb-3">
                      <label for="review_text" class="form-label fw-bold">Comments</label>
                      <input type="text" class="form-control" id="review_text" name="review_text">
                  </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
              </div>
          </form>
        </div>
      </div>
    </div>
{% endblock %}

restaurant_review/templates/restaurant_review/index.html
{% extends "restaurant_review/base.html" %}
{% load restaurant_extras %}
{% block title %}Restaurant List{% endblock %}
{% block content %}
  <h1>Restaurants</h1>

  {% if restaurants %}
      <table class="table">
          <thead>
              <tr>
                  <th>Name</th>
                  <th>Rating</th>
                  <th class="text-end">Details</th>
              </tr>
          </thead>
          <tbody>
              {% for restaurant in restaurants %}
                  <tr>
                      <td>{{ restaurant.name }}</td>
                      <td>{% star_rating restaurant.avg_rating restaurant.review_count   %}   </td>
                      <td class="text-end"><a href="{% url 'details' restaurant.id %}" class="btn btn-sm btn-primary">Details</a></td>
                  </tr>
              {% endfor %}
          </tbody>
      </table>
  {% else %}
      <p>No restaurants exist.  Select Add new restaurant to add one.</p>
  {% endif %}

  <div class="d-flex justify-content-end">
          <a href="{% url 'create_restaurant' %}" class="btn btn-success px-4 gap-3">Add new restaurant</a>
  </div>
{% endblock %}

restaurant_review/templates/restaurant_review/star_rating.html
{% if review_count %}
    <span class="score">
        <div class="score-wrap align-top">
            <span class="stars-active" style="width:{{stars_percent}}%">
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
            </span>
        <span class="stars-inactive">
                <i class="fa fa-star-o" aria-hidden="true"></i>
                <i class="fa fa-star-o" aria-hidden="true"></i>
                <i class="fa fa-star-o" aria-hidden="true"></i>
                <i class="fa fa-star-o" aria-hidden="true"></i>
                <i class="fa fa-star-o" aria-hidden="true"></i>
        </span>        
        </div>
        <span class="align-top">
            {{ avg_rating|floatformat:1 }} ({{review_count}} {% if review_count == 1 %} review{% else %} reviews{% endif %})
        </span>
    </span> 
{% else %}
  <span class="fst-italic">No ratings yet</span>
{% endif %}